apiVersion: v1
kind: Service
metadata:
  name: sql
spec:
  type: ClusterIP
  selector:
    app: sql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: myounis789/mysql:latest
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: 'petclinic'
        - name: MYSQL_DATABASE
          value: 'petclinic'